# Generated by Django 4.2.6 on 2023-10-15 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="friend_id",
            new_name="friend",
        ),
        migrations.RenameField(
            model_name="friend",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="wall_owner_id",
            new_name="wall_owner",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="user_id",
            new_name="user",
        ),
    ]
